eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.211.100:5600/eureka/,http://192.168.211.101:5600/eureka/
spring:
  aop:
    auto: true
    proxy-target-class: true
  mail:
    host: mail.aizhixin.com
    username: hr-1@aizhixin.com
    password: dinglicom#123
    default-encoding: UTF-8
  freemarker:
    content-type: text/html
    suffix: .html
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
  redis:
    host: 172.16.23.40
    port: 6379
    database: 4
    pool:
      max-active: 10
      max-idle: 10
      max-wait: 3
      min-idle: 1
  data:
    mongodb:
      database: file_system_test
      host: 172.16.23.23
      port: 27017
      password:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.23.21:3306/dledu_file_system?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 600000
      idle-timeout: 60000
      validation-timeout: 1000
      leak-detection-threshold: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming.strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE

liquibase:
  change-log: classpath:liquibase/master.xml
  default-schema: dledu_file_system

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dinglicom/gateway_access_log
      pattern: '%h %l %u [%{yyyy-MM-dd HH:mm:ss.SSS}t] "%r" %s %b %D'
      prefix: file_system_api_access_log
      suffix: .log
    basedir: /dinglicom/tmp/file_system_api
logging.level.com.aizhixin: INFO
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 60000
sys:
  version: v0.0.0.12
zookeeper:
  connecton: 192.168.211.100:2181,192.168.211.101:2181,192.168.211.102:2181
  path: /diandian/lock
  task: /diandian/task
zhixinapi:
  host: http://dledu.aizhixin.com/zhixin_api
  currentuser: /api/currentuser
  adduser: /api/account/add
  deleteuser: /api/account/delete/
  updatepassword: /api/account/updatepwd
  oauthtoken: /oauth/token
orgapi:
  host: http://gateway.dlztc.com/org-manager
  proflist: /v1/professionnal/list
  student: /v1/students/get
  org: /v1/org/get  
  orglist: /v1/org/droplist
  teacherlist: /v1/teacher/list
